# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\test\ui\test.ui'
#
# Created: Sun Nov 17 21:51:02 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(487, 131)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.URL_LE = QtWidgets.QLineEdit(Form)
        self.URL_LE.setObjectName("URL_LE")
        self.horizontalLayout.addWidget(self.URL_LE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Proxy_LE = QtWidgets.QLineEdit(Form)
        self.Proxy_LE.setObjectName("Proxy_LE")
        self.horizontalLayout_2.addWidget(self.Proxy_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Tag_LE = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tag_LE.sizePolicy().hasHeightForWidth())
        self.Tag_LE.setSizePolicy(sizePolicy)
        self.Tag_LE.setMinimumSize(QtCore.QSize(0, 0))
        self.Tag_LE.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Tag_LE.setObjectName("Tag_LE")
        self.horizontalLayout_3.addWidget(self.Tag_LE)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.Attr_LE = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Attr_LE.sizePolicy().hasHeightForWidth())
        self.Attr_LE.setSizePolicy(sizePolicy)
        self.Attr_LE.setObjectName("Attr_LE")
        self.horizontalLayout_3.addWidget(self.Attr_LE)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Param_LE = QtWidgets.QLineEdit(Form)
        self.Param_LE.setObjectName("Param_LE")
        self.horizontalLayout_3.addWidget(self.Param_LE)
        self.Republish_CB = QtWidgets.QCheckBox(Form)
        self.Republish_CB.setChecked(True)
        self.Republish_CB.setObjectName("Republish_CB")
        self.horizontalLayout_3.addWidget(self.Republish_CB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.Output_BTN = QtWidgets.QPushButton(Form)
        self.Output_BTN.setObjectName("Output_BTN")
        self.verticalLayout.addWidget(self.Output_BTN)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "网页文章 MarkDown 抓取器", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "抓取网址", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "代理设置", None, -1))
        self.Proxy_LE.setText(QtWidgets.QApplication.translate("Form", "127.0.0.1:12639", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "抓取标签", None, -1))
        self.Tag_LE.setText(QtWidgets.QApplication.translate("Form", "div", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "标签属性", None, -1))
        self.Attr_LE.setText(QtWidgets.QApplication.translate("Form", "class", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "属性参数", None, -1))
        self.Republish_CB.setText(QtWidgets.QApplication.translate("Form", "输出转载信息", None, -1))
        self.Output_BTN.setText(QtWidgets.QApplication.translate("Form", "输出 markdown 文件", None, -1))

